# higress-ai-demo: minikube local deployment (source-built images)
# Chart: higress/helm/core v2.2.4
global:
  local: true
  kind: false
  imagePullPolicy: IfNotPresent
  hub: registry.local
  tag: 2.2.4
  enablePluginServer: false

gateway:
  image: gateway
  service:
    type: NodePort
    ports:
      - name: http2
        port: 80
        protocol: TCP
        targetPort: 80
        nodePort: 30080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443
        nodePort: 30443

controller:
  image: higress

pilot:
  image: pilot

o11y:
  enabled: false

promtail:
  enabled: false