package com.example.aicuration.skills;

import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * Local skill: assemble a final daily-digest markdown document from the
 * pre-summarized sections. The agent calls this last, after gathering
 * articles and summarizing them, to produce the deliverable that the
 * notifier MCP tool will send.
 */
@Component
public class BuildDigestMarkdown {

    @Tool(description = """
        Build the final daily-digest markdown document. Takes the
        already-summarized bullet list and wraps it with a title, date
        header, and a footer. Returns the full markdown string ready to
        be sent via a notifier tool.
        """)
    public String build(
        @ToolParam(description = "Pre-summarized bullet list (markdown), "
            + "typically the output of summarize_articles.")
        String summaryMd,
        @ToolParam(description = "Optional digest title. Default: 'AI Daily Digest'.")
        String title
    ) {
        String t = (title == null || title.isBlank()) ? "AI Daily Digest" : title;
        String date = LocalDate.now(ZoneOffset.UTC).format(DateTimeFormatter.ISO_LOCAL_DATE);

        return """
            # %s — %s

            %s

            ---
            _Generated by spring-ai-demo (Skills + MCP) on %s_
            """.formatted(t, date, summaryMd.isBlank() ? "_(no items)_" : summaryMd, date);
    }
}
