package com.example.aicuration.skills;

import com.example.aicuration.domain.Article;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for the two local @Tool skills.
 *
 * <p>These are pure, deterministic skills so we can test them with hand-built
 * Article lists — no LLM mocking required.
 */
class SkillsTest {

    private static final Article A1 = new Article(
        "OpenAI releases GPT-5",
        "https://example.com/gpt5",
        "OpenAI Blog",
        Instant.parse("2026-08-08T01:00:00Z"),
        "GPT-5 is out"
    );

    private static final Article A2 = new Article(
        "DeepMind beats SOTA on math",
        "https://example.com/dm-math",
        "Google DeepMind Blog",
        Instant.parse("2026-08-08T03:00:00Z"),
        "AlphaProof update"
    );

    private static final Article A3 = new Article(
        "Old paper on CNNs",
        "https://example.com/old",
        "MIT News",
        Instant.parse("2020-01-01T00:00:00Z"),
        "Background"
    );

    private final SummarizeArticles summarize = new SummarizeArticles();
    private final BuildDigestMarkdown build = new BuildDigestMarkdown();

    @Test
    void summarize_orders_by_published_at_desc_and_caps() {
        // Build JSON array string (simulating the MCP tool's return)
        String json = """
            [
              {"title": "OpenAI releases GPT-5", "url": "https://example.com/gpt5", "source": "OpenAI Blog", "published_at": "2026-08-08T01:00:00Z", "snippet": "GPT-5 is out"},
              {"title": "DeepMind beats SOTA on math", "url": "https://example.com/dm-math", "source": "Google DeepMind Blog", "published_at": "2026-08-08T03:00:00Z", "snippet": "AlphaProof update"},
              {"title": "Old paper on CNNs", "url": "https://example.com/old", "source": "MIT News", "published_at": "2020-01-01T00:00:00Z", "snippet": "Background"}
            ]
            """;

        String out = summarize.summarize(json, 2);

        // Newest 2 (A2 then A1), A3 dropped
        assertTrue(out.contains("DeepMind beats SOTA on math"), "should contain A2 first");
        assertTrue(out.contains("OpenAI releases GPT-5"), "should contain A2 second");
        assertFalse(out.contains("Old paper on CNNs"), "A3 should be dropped by max=2");
        // Sort: A2 before A1
        assertTrue(out.indexOf("DeepMind") < out.indexOf("OpenAI"), "A2 (newer) should appear before A1");
    }

    @Test
    void summarize_handles_empty_input() {
        assertEquals("_(no articles found)_", summarize.summarize("[]", 10));
        assertEquals("_(no articles found)_", summarize.summarize("", 10));
    }

    @Test
    void summarize_handles_invalid_json_as_empty() {
        // The MCP tool returns "ERROR: ..." strings sometimes; treat as empty
        String out = summarize.summarize("ERROR: something went wrong", 10);
        assertEquals("_(no articles found)_", out);
    }

    @Test
    void build_wraps_summary_in_full_markdown_doc() {
        String summary = "- [Title](https://x) _Source_";
        String doc = build.build(summary, "My Digest");

        assertTrue(doc.startsWith("# My Digest — "), "should start with title + date");
        assertTrue(doc.contains(summary), "should contain the summary verbatim");
        assertTrue(doc.contains("---"), "should have a horizontal rule footer");
        assertTrue(doc.contains("_Generated by spring-ai-demo"), "should have footer attribution");
    }

    @Test
    void build_uses_default_title_when_blank() {
        String doc = build.build("- item", "");
        assertTrue(doc.startsWith("# AI Daily Digest — "), "should fall back to default title");
    }
}
